using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;
using SemanticPortrait.App.Services;
using SemanticPortrait.Core;

namespace SemanticPortrait.App.Components.Pages;

// The chat loop: sending entries, streaming replies, tool bubbles, onboarding, and the
// hand-off to the clean-room analyst.
public partial class Home
{
    /// <summary>The live privacy facts for the system prompt — the agent describes the privacy
    /// model from THIS, never from vibes (Prompts §Privacy honesty). Local provider = the full
    /// loop stays on-device; cloud = entry text leaves, masked or not per the user's consent.</summary>
    private string PrivacyLine()
    {
        if (Ai.ProviderId == "lmstudio")
            return $"Privacy state: storage local+encrypted; provider {Ai.DisplayName} runs LOCALLY — nothing leaves this machine.";
        var masking = Microsoft.Maui.Storage.Preferences.Default.Get("masking", false);
        return $"Privacy state: storage local+encrypted; replies are generated by {Ai.DisplayName} (CLOUD — " +
               $"entry text leaves this machine, {(masking ? "PII-masked first" : "masking is OFF")}).";
    }

    /// <summary>Have the agent post an unprompted message (reminders, the post-import welcome).
    /// Gets the read-only recall tools so a proactive message can be GROUNDED in the portrait —
    /// the post-import continuation greeting is exactly a recall-then-speak move.</summary>
    private async Task FireProactive(string kickInstruction)
    {
        if (_busy) return;
        _busy = true;
        var sys = Prompts.Analyst + $"\n\n## Now\nCurrent time: {DateTime.Now:dddd, MMM d, yyyy h:mm tt}.\n{PrivacyLine()}";
        var reply = new Msg { Role = "ai", Text = "", Streaming = true };
        _messages.Add(reply); _scrollDown = true; StateHasChanged();
        var specs = Tools.ReadSpecs.Concat(Recall.MainSpecs).ToList();
        async Task<string> Exec(string name, string args)
        {
            var result = Recall.Handles(name) ? await Recall.ExecuteAsync(name, args)
                : await Tools.ExecuteAsync(name, args);
            _messages.Remove(reply);
            AddToolBubble(FriendlyToolNote(name), $"params: {args}\nresult: {result}");
            _messages.Add(reply);
            StateHasChanged();
            return result;
        }
        var perr = new ProviderErrs();
        var clean = new System.Text.StringBuilder();
        try
        {
            using var watchdog = new System.Threading.CancellationTokenSource(TimeSpan.FromMinutes(4));
            await foreach (var tok in Ai.StreamReplyAsync(sys, new[] { new ChatMessage("user", kickInstruction) }, specs, Exec,
                onError: err =>
                {
                    if (perr.ReportAndShouldShow(err)) reply.Text += $"{(reply.Text.Length > 0 ? "\n" : "")}⚠️ {FriendlyProviderError(err)}";
                    DevTrap.Report("proactive-provider", new InvalidOperationException(err));
                },
                ct: watchdog.Token))
            {
                if (perr.IsErrToken(tok)) continue;
                reply.Text += tok; clean.Append(tok); _scrollDown = true; StateHasChanged();
            }
        }
        catch (Exception e) { DevTrap.Report("proactive-stream", e); }
        finally
        {
            reply.Streaming = false;
            if (!string.IsNullOrWhiteSpace(clean.ToString())) await Persist("assistant", clean.ToString());
            _busy = false; _focusNext = true; StateHasChanged();
        }
    }

    /// <summary>
    /// Provider-error bookkeeping for one streamed reply. The client reports an error via
    /// onError AND yields the same text inline (for bare consumers) — this UI uses onError,
    /// so the inline copy must be skipped or the error shows twice. It also keeps error text
    /// out of what gets persisted: an error stored as an assistant message becomes thread
    /// history the model re-reads (and compacts, and embeds) forever after.
    /// </summary>
    private sealed class ProviderErrs
    {
        private readonly HashSet<string> _raw = new();
        public bool Any => _raw.Count > 0;
        /// <summary>True only for the FIRST error of the stream — later ones (the provider often
        /// sends the same failure as both an `error` event and `response.failed`) stay off-screen.</summary>
        public bool ReportAndShouldShow(string err) => _raw.Add(err) && _raw.Count == 1;
        public bool IsErrToken(string tok) => _raw.Contains(tok);
    }

    /// <summary>Translate raw provider errors the user can act on into plain instructions.</summary>
    private static string FriendlyProviderError(string err) =>
        err.Contains("insufficient_quota") || err.Contains("exceeded your current quota")
            ? "your AI provider account is out of credit. Add credit (for OpenAI: platform.openai.com → Billing) " +
              "or switch provider/key in ⋯ → LLM settings, then send your message again."
            : err;

    private HandoffDeduper? _handoffDedup;   // session-scoped send_to_analysis duplicate gate
    private bool _greeting;
    /// <summary>Proactively open a brand-new thread: the agent greets and starts onboarding.</summary>
    private async Task GreetOnboarding()
    {
        if (_greeting || _busy) return;
        _greeting = true; _busy = true;

        var sys = Prompts.Analyst + $"\n\n## Now\nCurrent time: {DateTime.Now:dddd, MMM d, yyyy h:mm tt}. " +
                  $"This is a brand-new, empty thread.\n{PrivacyLine()}";
        var kick = new[] { new ChatMessage("user",
            "[A fresh thread just started. Greet me warmly in one short line, orient me in one more — " +
            "honestly, per your Privacy honesty section and the Privacy state line (continuous, never " +
            "deleted, encrypted on this machine; replies via my chosen AI provider) — then offer the " +
            "~10-minute intake per your onboarding section, including that I can say 'skip' to any " +
            "question or 'just start' to skip it all, and ask the first question (my name). Keep it " +
            "light; no wall of text.]") };

        var reply = new Msg { Role = "ai", Text = "", Streaming = true };
        await InvokeAsync(() => { _messages.Add(reply); _scrollDown = true; StateHasChanged(); });
        var perr = new ProviderErrs();
        var clean = new System.Text.StringBuilder();
        try
        {
            using var watchdog = new System.Threading.CancellationTokenSource(TimeSpan.FromMinutes(4));
            await foreach (var tok in Ai.StreamReplyAsync(sys, kick,
                onError: err =>
                {
                    if (perr.ReportAndShouldShow(err)) reply.Text += $"{(reply.Text.Length > 0 ? "\n" : "")}⚠️ {FriendlyProviderError(err)}";
                    DevTrap.Report("greet-provider", new InvalidOperationException(err));
                },
                ct: watchdog.Token))
            {
                if (perr.IsErrToken(tok)) continue;
                reply.Text += tok; clean.Append(tok); _scrollDown = true;
                await InvokeAsync(StateHasChanged);
            }
        }
        catch (Exception e) { DevTrap.Report("greet-stream", e); }
        finally
        {
            reply.Streaming = false;
            // Persist real content only — a failed greeting must not save, so the next
            // launch sees an empty thread and simply greets again.
            if (!string.IsNullOrWhiteSpace(clean.ToString())) await Persist("assistant", clean.ToString());
            _busy = false; _greeting = false; _focusNext = true;
            await InvokeAsync(StateHasChanged);
        }
    }

    private static string FriendlyToolNote(string tool) => tool switch
    {
        "set_profile_field"  => "📝 noted who you are",
        "get_profile"        => "🔎 recalled what I know about you",
        "search_memory"      => "🔎 looked back through your thread",
        "search_past_analysis" => "🔎 reviewed past analysis",
        "recall"             => "🔎 gathered the full context",
        "record_intake_progress" => "📋 intake progress",
        "portrait"           => "✦ read your constellation",
        "list_node_labels"   => "✦ checked the map's labels",
        "send_to_analysis"   => "🧠 sent to deep analysis",
        "save_note"          => "📝 saved an insight",
        "refine_note"        => "✏️ refined an earlier note",
        "record_entry_meta"  => "🗒 logged your state",
        "import_entry"       => "📥 relived an entry",
        "log_event"          => "🗓 logged an event",
        "upsert_node"        => "✦ added to your map",
        "link_nodes"         => "✦ connected the map",
        "add_todo"           => "✅ added a todo",
        "list_todos"         => "📋 checked your todos",
        "complete_todo"      => "✅ checked off a todo",
        "set_reminder"       => "⏰ set a reminder",
        "upcoming"           => "🗓 checked your agenda",
        "privacy_status"     => "🛡 checked what leaves this machine",
        "voice_setup"        => "🎙 checked voice setup",
        "set_evening_checkin" => "🌙 set the evening check-in",
        "list_reminders"     => "⏰ checked your reminders",
        "cancel_reminder"    => "⏰ cancelled a reminder",
        "make_prediction"    => "🎯 logged a prediction",
        "list_open_predictions" => "🎯 checked open predictions",
        "resolve_prediction" => "🎯 scored a prediction",
        _                     => "🔧 tool call",
    };

    /// <summary>Persist a tool-call as an expandable bubble in the thread.</summary>
    private void AddToolBubble(string label, string detail)
    {
        Database.AddMessage("tool", label, DateTime.UtcNow.ToString("o"), detail);
        _messages.Add(new() { Role = "tool", Text = label, Detail = detail });
        _scrollDown = true;
    }

    private async Task OnKey(KeyboardEventArgs e)
    {
        if (e.Key == "Enter" && !e.ShiftKey) await Send();
    }

    private async Task Send()
    {
        // A photo-only entry is valid — allow send when there's text OR pending photos.
        if (_busy || (string.IsNullOrWhiteSpace(_draft) && _pendingPhotos.Count == 0)) return;
        _busy = true;
        ResetIdle();

        var userText = _draft.Trim();
        // Photos ride WITH the entry: a tag keeps a photo-only entry from embedding empty text and
        // tells the analyst something visual was shared (it can't see pixels, but it knows they exist).
        var photoTag = _pendingPhotos.Count is var pn and > 0 ? $"[shared {pn} photo{(pn == 1 ? "" : "s")}]" : "";
        var persistText = string.IsNullOrEmpty(photoTag) ? userText
            : (userText.Length > 0 ? userText + "\n" + photoTag : photoTag);

        // Temporal context: how long since their last message (before we add this one).
        var prev = Database.GetMessages().LastOrDefault(m => m.Role is "user" or "assistant");
        var sincePhrase = prev is null ? "This is their first message." : $"Time since their last message: {Elapsed(prev.CreatedUtc)}.";

        var userBubble = new Msg { Role = "user", Text = userText };
        _messages.Add(userBubble);
        _draft = "";

        // The thinking bubble goes up IMMEDIATELY — the embed + compaction below can take whole
        // seconds (compaction is a provider call when a backlog aged out), and without a bubble
        // that pre-work reads as the app freezing on send.
        var reply = new Msg { Role = "ai", Text = "", Streaming = true };
        _messages.Add(reply);
        _scrollDown = true;
        StateHasChanged();

        // Persist + embed the journal entry; keep its id for metadata attribution.
        var entryId = await Persist("user", persistText);
        // Attach the pending photos to the saved entry (encrypted blobs) and hydrate the bubble.
        userBubble.DbId = entryId;
        if (entryId > 0) AttachPendingTo(entryId, userBubble);

        // Compaction: fold anything older than the 2-day window into a rolling summary
        // (full detail stays searchable in the vec DB). Best-effort.
        try { await Compaction.EnsureCompactedAsync(DateTime.UtcNow); }
        catch (Exception e) { DevTrap.Report("compaction-send", e); }

        // In-flight history = only the last 2 days, verbatim, from the DB (real timestamps).
        var cutoff = Compaction.CutoffUtc(DateTime.UtcNow);
        var history = Database.GetMessages()
            .Where(m => m.Role is "user" or "assistant")
            .Where(m => Compactor.ParseUtc(m.CreatedUtc) > cutoff)
            .Select(m => new ChatMessage(m.Role == "user" ? "user" : "assistant", m.Text))
            .ToList();

        // Temporal awareness preamble: current time + elapsed since last message.
        // Interrupted-intake status: computed DETERMINISTICALLY from the counter state (not from
        // the model's memory of where it was). Surfacing it here — rather than relying on a tool
        // lookup — makes resumption survive an app restart and the 2-day compaction window aging
        // the intake out of view. Null once complete/aborted: finished intakes cost zero context.
        var intakeStatus = Intake.StatusLine();
        var intakeLine = intakeStatus is null ? "" : "\n" + intakeStatus;

        var nowBlock = $"## Now\nCurrent time: {DateTime.Now:dddd, MMM d, yyyy h:mm tt}. {sincePhrase}\n" +
            "Calibrate to this: a short greeting after a long gap is a FRESH check-in — greet and ask " +
            "what's up; don't assume the previous topic is still active. A quick reply moments later " +
            "continues the same thread.\n" + PrivacyLine() + intakeLine;

        // Older context arrives as a compacted preamble appended to the system prompt.
        var summary = Compaction.CurrentSummary();
        var systemPrompt = Prompts.Analyst + "\n\n" + nowBlock
            + (summary.Length > 0 ? "\n\n## Earlier context (older than 2 days, compacted — use recall for specifics)\n" + summary : "");

        // Main agent gets READ-ONLY tools (recall for grounded delivery). All durable WRITES
        // happen in the clean analyst subagent, so user steering can't poison the stored model.
        // recall (joined bundle: hits + mood + exchange + person + timeline) replaces the old
        // flat search_memory; portrait gives the interconnected view of one person/theme.
        // Exception: the intake counter is an operational write (worst-case poisoning = a wrong
        // count), offered ONLY while the intake is unfinished — it vanishes from specs after.
        var specs = Tools.ReadSpecs.Concat(Recall.MainSpecs).Concat(Tasks.Specs).Concat(Privacy.Specs)
            .Concat(_voiceTools is { } vt ? vt.Specs : Array.Empty<object>())
            .Concat(Intake.IsComplete() ? Array.Empty<object>() : Intake.Specs)
            .Append(HandoffSpec).ToList();
        async Task<string> Exec(string name, string args)
        {
            if (name == "send_to_analysis")
            {
                string payload;
                try { using var d = System.Text.Json.JsonDocument.Parse(args);
                      payload = d.RootElement.TryGetProperty("data", out var p) ? (p.GetString() ?? "") : ""; }
                catch { payload = ""; }
                if (!string.IsNullOrWhiteSpace(payload))
                {
                    // A SENSE, not a wall: the model has no memory of what it already handed off
                    // (observed live: same arc twice, same safety check-in three times). The tool
                    // supplies that memory — what a repeat matched, and a ledger of what's gone —
                    // and hands the judgment back: genuinely new information, distilled to just
                    // the delta, won't match and goes straight through.
                    _handoffDedup ??= new HandoffDeduper(Embedder);
                    if (await _handoffDedup.MatchAsync(payload) is { } matched)
                        return $"this closely matches a hand-off you already made (\"{matched}\") — the analyst has it. " +
                               "If this repeat adds something NEW, send again with ONLY the new part; " +
                               "if it's the same hand-off re-told, you're done — don't re-send.";
                    _ = ReflectInBackground(entryId, userText, payload).Guard("reflect-background");   // deep analyst
                    return $"handed to the analyst (analyzing in the background). Your hand-offs {_handoffDedup.Ledger()}";
                }
                return "handed to the analyst (analyzing in the background)";
            }
            var result = Tasks.Handles(name) ? await Tasks.ExecuteAsync(name, args)
                : Privacy.Handles(name) ? await Privacy.ExecuteAsync(name, args)
                : _voiceTools is { } vtl && vtl.Handles(name) ? await vtl.ExecuteAsync(name, args)
                : Intake.Handles(name) ? await Intake.ExecuteAsync(name, args)
                : Recall.Handles(name) ? await Recall.ExecuteAsync(name, args)
                : Memory.Handles(name) ? await Memory.ExecuteAsync(name, args)
                : await Tools.ExecuteAsync(name, args);
            if (name is "recall" or "search_memory") reply.Sourced = true;   // cite the journal under the reply
            var detail = $"params: {args}\nresult: {result}";
            Trace.Add("main", "tool", name, detail);
            _messages.Remove(reply);
            AddToolBubble(FriendlyToolNote(name), detail);   // persisted + expandable
            _messages.Add(reply);
            StateHasChanged();
            return result;
        }

        var perr = new ProviderErrs();
        var clean = new System.Text.StringBuilder();   // reply text WITHOUT error/stall notices — the only part safe to persist
        try
        {
            // Stall watchdog: a wedged stream never trips HttpClient.Timeout once headers arrive
            // (observed live: 21 min at 0% CPU) — without this, _busy pins forever and the
            // composer is dead until an app restart. Generous cap: multi-tool turns are slow,
            // dead streams are forever.
            using var watchdog = new System.Threading.CancellationTokenSource(TimeSpan.FromMinutes(5));
            await foreach (var token in Ai.StreamReplyAsync(systemPrompt, history, specs, Exec,
                onReasoning: r => Trace.Add("main", "thought", "reasoning", r),
                // A silent provider failure looks like the agent "just stopped thinking" —
                // surface it in the bubble (actionable for the user) and the dev channels.
                onError: err =>
                {
                    if (perr.ReportAndShouldShow(err)) reply.Text += $"{(reply.Text.Length > 0 ? "\n" : "")}⚠️ {FriendlyProviderError(err)}";
                    DevTrap.Report("send-provider", new InvalidOperationException(err));
                },
                ct: watchdog.Token))
            {
                if (perr.IsErrToken(token)) continue;   // inline copy of an already-shown error
                reply.Text += token;
                clean.Append(token);
                _scrollDown = true;
                StateHasChanged();
            }
        }
        catch (OperationCanceledException)
        {
            reply.Text += "\n[the reply stalled and was cancelled — send again to retry]";
            DevTrap.Report("send-stream-stalled", new TimeoutException("main stream watchdog fired (5 min)"));
        }
        catch (Exception ex)
        {
            reply.Text += $"\n[stream error: {ex.Message}]";
        }
        finally
        {
            reply.Streaming = false;
            // Persist + embed the analyst note (real content only — never error notices).
            if (!string.IsNullOrWhiteSpace(clean.ToString()))
                await Persist("assistant", clean.ToString());

            _busy = false;
            _focusNext = true;   // refocus the composer so the user can keep typing
            StateHasChanged();
            // Analysis is now triggered by the main agent via send_to_analysis (after it refines),
            // not automatically on every turn.
        }
    }

    // Tool: main agent hands refined data to the deep analyst.
    private static readonly object HandoffSpec = new
    {
        type = "function",
        name = "send_to_analysis",
        description = "Hand a clean, distilled summary of something worth remembering (a real entry, " +
                      "insight, event, or decision) to the deep background analyst, which updates the " +
                      "long-term model + graph. It cannot see this chat, so put everything it needs in " +
                      "'data'. Don't call on small talk or half-formed thoughts — refine first.",
        parameters = new
        {
            type = "object",
            properties = new { data = new { type = "string", description = "The distilled content to analyze + remember." } },
            required = new[] { "data" },
            additionalProperties = false,
        },
    };

    /// <summary>Run the clean analyst subagent (un-poisoned) to update long-term memory.
    /// Gets the user's RAW entry (word choices are load-bearing for entry_meta) plus the anchor's
    /// distillation. The anchor's reply isn't passed — it's still streaming when the hand-off fires.</summary>
    private async Task ReflectInBackground(long entryId, string rawEntry, string distilled)
    {
        // Surface each clean-analyst tool call as a persisted, expandable bubble (append-only —
        // nothing is removed, so the bubbles stay put for inspection).
        void OnAnalystTool(string name, string detail) =>
            _ = InvokeAsync(() =>
            {
                AddToolBubble("🧠 " + FriendlyToolNote(name), detail);
                _scrollDown = true;
                StateHasChanged();
            });

        var failed = false;
        try
        {
            // Watchdog: a wedged analyst stream would silently strand the reflection forever;
            // cancelling routes it into the retry queue like any provider failure.
            using var watchdog = new System.Threading.CancellationTokenSource(TimeSpan.FromMinutes(8));
            await Analyst.ReflectAsync(entryId, rawEntry, distilled, "", OnAnalystTool,
                onProviderError: _ => failed = true, ct: watchdog.Token);
        }
        catch (Exception e) { failed = true; DevTrap.Report("reflect", e); }

        if (failed)
        {
            // Offline / provider down: capture is already stored; the ANALYSIS waits in the
            // queue and retries on the background tick once the provider is reachable again.
            // Only the distillation is queued — the raw entry is re-fetched by entry_id at drain time.
            try { Database.EnqueueAnalysis(entryId, distilled); }
            catch (Exception e) { DevTrap.Report("enqueue-analysis", e); }   // lost retry = silent memory gap
            await Note("🧠 analysis queued — provider unreachable; will retry automatically.");
        }

        await InvokeAsync(() =>
        {
            LoadGraph();          // the subagent may have added nodes/edges
            SaveMetricsSnapshot();
            StateHasChanged();
        });
    }

    /// <summary>Store a message and (best-effort) its embedding for vector search. Returns the message id.</summary>
    private async Task<long> Persist(string role, string text)
    {
        try
        {
            var id = Database.AddMessage(role, text, DateTime.UtcNow.ToString("o"));
            var vec = await Embedder.EmbedAsync(text);
            if (vec is not null) Database.AddEmbedding("message", id, vec);
            return id;
        }
        catch { return 0; }   // don't let persistence break the conversation
    }
}
